language: python
python:
  - "2.7"
  - "3.3"
install:
  - python setup.py install
script:
  - python setup.py test
notifications:
  email:
    recipients:
      - anler86@gmail.com
    on_success: change
    on_failure: change
